script:
  - 'build/deploy.rb'

language: ruby
before_install:
  - gem install sass haml haml-contrib maruku

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: main
